name: BestProject

pipelines:
  provider: github
  owner: BestOrg
  repo: BestRepo
  lint: true
  test: true
  coverage: true

vcs:
  provider: github
  owner: BestOrg
  repo: BestRepo
  visibility: public

application:
  language:
    name: javascript
    version: emca7
    framework:
      name: express
      version: 4.17.1
  version: 1.0.0
  services:
    - name: api
      type: http
      description: REST API
      version: 1.0.0
    - name: database
      type: postgres
      version: 15.*
      port: 5432
      env:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    - name: cache
      type: redis
      version: 5.0.0

environments:
  dev:
    deploy:
      target: local
    orchestrator: compose
  stage:
    deploy:
      target: aws
      nodes:
        - type: t4g.small
          services:
            - name: database
              min: 1
              max: 1
          min: 1
          max: 1
        - type: t4g.small
          services:
            - name: database
              min: 1
              max: 1
            - name: cache
              min: 1
              max: 1
          min: 1
          max: 1
      regions:
        - us-east-1
    orchestrator: kubernetes
  prod:
    deploy:
      target: aws
      regions:
        - us-east-1
        - us-west-2
